# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wof.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wof.proto',
  package='wof',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\twof.proto\x12\x03wof\"\x19\n\x0bPlayerOrder\x12\n\n\x02id\x18\x01 \x03(\t'
)




_PLAYERORDER = _descriptor.Descriptor(
  name='PlayerOrder',
  full_name='wof.PlayerOrder',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='wof.PlayerOrder.id', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=43,
)

DESCRIPTOR.message_types_by_name['PlayerOrder'] = _PLAYERORDER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlayerOrder = _reflection.GeneratedProtocolMessageType('PlayerOrder', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERORDER,
  '__module__' : 'wof_pb2'
  # @@protoc_insertion_point(class_scope:wof.PlayerOrder)
  })
_sym_db.RegisterMessage(PlayerOrder)


# @@protoc_insertion_point(module_scope)
